-- v1.56.0 — emergency staff password reset from the Super Admin panel
--
-- REQUESTED: "ak bnda pass bhol gya din ka ya caser ka pos open he nhi hota is
-- leyi ye option emergency rkho super admin penal me" — a cashier forgets their
-- password, the POS will not open, and there is nobody above them who can let
-- them back in. And, explicitly: "ye user pass ka forget krny ka option super
-- admin me ho, ye nhi ky super admin pass krna" — this resets a RESTAURANT's
-- staff password, not the Super Admin's own.
--
-- WHY A NEW FUNCTION RATHER THAN THE EXISTING ONE. pos_update_user() already
-- changes a staff password, but it opens with
--
--     v_tenant uuid := auth_tenant_id();
--     if v_tenant is null or auth_role() not in ('owner','admin') then raise ...
--
-- A Super Admin has no tenant, so auth_tenant_id() is null and every attempt
-- was refused — correctly. Widening pos_update_user to accept a Super Admin
-- would put a cross-tenant branch inside the function every restaurant's own
-- admin calls, which is exactly where such a branch should not be. These are
-- separate functions with a single guard each.
--
-- WHAT KEEPS THIS FROM BEING A BACKDOOR
--
--   * is_super_admin() is the only way in. It reads super_admins by auth.uid(),
--     so a restaurant admin, a portal token and anon all get 'forbidden'.
--   * must_change_password is set, and v1.31.1 made LoginPage refuse to finish
--     a login while it is true. So the temporary password can be used exactly
--     once, to choose a real one; the Super Admin's copy stops working the
--     moment the staff member sets their own.
--   * Every reset is written to staff_audit_logs against the restaurant, with
--     the Super Admin's own id and email, so the restaurant can see who did it
--     and when. Nothing here is silent.
--   * The existing hash is never read, returned or logged. Passwords are
--     stored bcrypt (crypt/gen_salt('bf')) exactly as pos_update_user does.
--   * The last active admin cannot be locked out: the reset never changes a
--     role or is_active, only the password.
--
-- Idempotent: CREATE OR REPLACE only. No existing row is deleted.

-- --------------------------------------------------------------------------
-- Who can be reset: the staff of one restaurant, for the picker.
-- Never returns pin_hash.
-- --------------------------------------------------------------------------
create or replace function public.sa_list_staff(p_tenant uuid)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'public', 'extensions'
as $$
declare v jsonb;
begin
  if not public.is_super_admin() then
    return jsonb_build_object('ok', false, 'reason', 'forbidden');
  end if;
  if p_tenant is null then
    return jsonb_build_object('ok', false, 'reason', 'no_restaurant');
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
           'userId',   u.user_id,
           'username', u.username,
           'name',     u.display_name,
           'role',     u.role,
           'phone',    u.phone,
           'branchId', u.branch_id,
           'isActive', u.is_active,
           'mustChangePassword', u.must_change_password,
           'hasPassword', u.pin_hash is not null,
           'updatedAt', u.updated_at
         ) order by u.is_active desc, u.role, u.display_name), '[]'::jsonb) into v
    from public.user_profiles u
   where u.tenant_id = p_tenant;

  return jsonb_build_object('ok', true, 'staff', v,
    'workspaceCode', (select workspace_code from public.tenants where id = p_tenant),
    'restaurant',    (select name           from public.tenants where id = p_tenant));
end
$$;

-- --------------------------------------------------------------------------
-- The reset itself.
--
-- p_new_password is optional: left null, a readable one is generated by the
-- existing generate_initial_password(), whose alphabet already excludes the
-- characters people misread over a phone (O/0, I/l/1).
-- --------------------------------------------------------------------------
create or replace function public.sa_reset_staff_password(
  p_user_id uuid,
  p_new_password text default null,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'public', 'extensions'
as $$
declare
  u        record;
  v_pass   text;
  v_admin  uuid := auth.uid();
  v_email  text;
begin
  if not public.is_super_admin() then
    return jsonb_build_object('ok', false, 'reason', 'forbidden');
  end if;

  select user_id, tenant_id, branch_id, username, display_name, role, is_active
    into u
    from public.user_profiles
   where user_id = p_user_id;

  if u.user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'no_user');
  end if;

  -- A password a person has to read out and type. Short enough to dictate,
  -- long enough not to be guessed; 10 is the floor the generator enforces.
  v_pass := nullif(btrim(coalesce(p_new_password, '')), '');
  if v_pass is null then
    v_pass := public.generate_initial_password(10);
  elsif length(v_pass) < 4 then
    return jsonb_build_object('ok', false, 'reason', 'too_short',
      'message', 'Password must be at least 4 characters.');
  end if;

  update public.user_profiles
     set pin_hash             = crypt(v_pass, gen_salt('bf')),
         -- The staff member must choose their own on the way in, so this
         -- temporary one cannot quietly become the permanent password.
         must_change_password = true,
         updated_at           = now()
   where user_id = p_user_id;

  select email into v_email from auth.users where id = v_admin;

  -- The restaurant is entitled to know. Written against THEIR tenant so it
  -- shows up in their own audit history, not only ours.
  insert into public.staff_audit_logs
    (tenant_id, branch_id, user_id, user_name, user_role, action, reason, meta)
  values (
    u.tenant_id, u.branch_id, u.user_id, u.display_name, u.role,
    'SUPER_ADMIN_PASSWORD_RESET',
    nullif(btrim(coalesce(p_reason, '')), ''),
    jsonb_build_object(
      'username',       u.username,
      'bySuperAdminId', v_admin,
      'bySuperAdmin',   coalesce(v_email, 'super admin'),
      'at',             now()
    )
  );

  return jsonb_build_object(
    'ok', true,
    'username', u.username,
    'name', u.display_name,
    'role', u.role,
    'isActive', u.is_active,
    -- Returned ONCE, to be read out to the person locked out. It is not
    -- stored anywhere in clear text; only its bcrypt hash was written.
    'password', v_pass,
    'mustChangePassword', true
  );
end
$$;

revoke all on function public.sa_list_staff(uuid) from public, anon;
revoke all on function public.sa_reset_staff_password(uuid, text, text) from public, anon;
grant execute on function public.sa_list_staff(uuid) to authenticated;
grant execute on function public.sa_reset_staff_password(uuid, text, text) to authenticated;
