-- ============================================================================
-- v1.32.0 — the last two customer-app features: an ID the shop can quote, and
--           a profile photo.
--
-- ASKED FOR: "custumer me profile ho photo ke sath, custumer id resturant ko
-- dikhy". The uuid was the only identifier a customer had, and nobody reads a
-- uuid down a phone line.
--
-- THE CODE
-- Short, unique WITHIN a restaurant (two restaurants may both hold C-4F2A9 and
-- neither can see the other's customers anyway), and drawn from an alphabet
-- with no 0/O and no 1/l/I — this gets spoken across a counter and typed off a
-- screen. Generated by a trigger, and backfilled: a feature that only works for
-- customers created after today is not the feature that was asked for.
--
-- THE PHOTO — AND WHY THE BROWSER NEVER WRITES IT
-- The customer-photos bucket has a public READ policy and NO write policy at
-- all, so only the service key can put a file in it. That is deliberate: an
-- anon INSERT policy on storage is precisely the shape of the hole found on
-- order_items in v1.31.0, where anyone holding the public key could write.
-- Uploads go through the uploadCustomerPhoto server function, which resolves
-- the session token in Postgres and derives the storage path from the ANSWER —
-- so a customer can only ever replace their own photo, because the path is not
-- theirs to choose.
--
-- public_customer_set_photo additionally refuses any URL that does not point at
-- our own bucket, or this would become a way to park arbitrary links on a
-- customer record.
--
-- READ-ONLY IN THE POS: neither column is in supabaseStore's ALLOWED_COLUMNS.
-- The POS displays both and can overwrite neither — the code would collide,
-- and the photo is not the shop's to change.
--
-- VERIFIED LIVE (rolled back): 1498 of 1498 customers hold a code, no
-- duplicates within a tenant, samples C-NJNXX / C-DZ29B / C-WFEP4;
-- a valid bucket URL saves; an outside URL is refused with bad_url;
-- a junk token is refused with no_session; clearing works.
-- ============================================================================

alter table public.customers add column if not exists customer_code text;
alter table public.customers add column if not exists photo_url     text;

create unique index if not exists customers_code_per_tenant
  on public.customers (tenant_id, customer_code)
  where customer_code is not null;

create or replace function public.generate_customer_code(p_tenant uuid)
returns text
language plpgsql
volatile
security definer
set search_path to 'pg_catalog', 'public', 'extensions'
as $function$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  candidate text;
  i integer;
  attempt integer := 0;
begin
  loop
    candidate := 'C-';
    for i in 1..5 loop
      candidate := candidate || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
    end loop;
    exit when not exists (
      select 1 from public.customers
       where tenant_id = p_tenant and customer_code = candidate);
    attempt := attempt + 1;
    -- 32^5 is 33 million per restaurant; twenty collisions means something is
    -- wrong, and looping forever would be worse than a longer code.
    if attempt > 20 then
      candidate := 'C-' || upper(substr(md5(random()::text), 1, 8));
      exit;
    end if;
  end loop;
  return candidate;
end $function$;

create or replace function public.assign_customer_code()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if new.customer_code is null then
    new.customer_code := public.generate_customer_code(new.tenant_id);
  end if;
  return new;
end $function$;

drop trigger if exists trg_assign_customer_code on public.customers;
create trigger trg_assign_customer_code
  before insert on public.customers
  for each row execute function public.assign_customer_code();

update public.customers
   set customer_code = public.generate_customer_code(tenant_id)
 where customer_code is null;

create or replace function public.customer_public_json(c public.customers)
returns jsonb
language sql
stable
set search_path to 'public'
as $function$
  select jsonb_build_object(
    'id',            c.id,
    'customerCode',  c.customer_code,
    'photoUrl',      c.photo_url,
    'name',          c.name,
    'phone',         c.phone,
    'email',         c.email,
    'address',       c.address,
    'city',          c.city,
    'area',          c.area,
    'fullAddress',   c.full_address,
    'addresses',     coalesce(c.addresses, '[]'::jsonb),
    'dateOfBirth',   c.date_of_birth,
    'gender',        c.gender,
    'lat',           c.lat,
    'lng',           c.lng,
    'loyaltyPoints', c.loyalty_points,
    'totalOrders',   c.total_orders,
    'lastOrderAt',   c.last_order_at);
$function$;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('customer-photos', 'customer-photos', true, 2097152,
        array['image/jpeg','image/png','image/webp'])
on conflict (id) do update
  set public = true,
      file_size_limit = 2097152,
      allowed_mime_types = array['image/jpeg','image/png','image/webp'];

drop policy if exists "customer-photos_public_read" on storage.objects;
create policy "customer-photos_public_read" on storage.objects
  for select to public using (bucket_id = 'customer-photos');
-- NO write policy on purpose. See the header.

create or replace function public.public_customer_set_photo(p_token text, p_url text)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'extensions'
as $function$
declare
  v_row public.customers := customer_from_token(p_token);
  v_url text := nullif(btrim(coalesce(p_url, '')), '');
begin
  if v_row.id is null then return jsonb_build_object('ok', false, 'reason', 'no_session'); end if;
  if customer_app_blocked(v_row.tenant_id) then
    return jsonb_build_object('ok', false, 'reason', 'app_disabled');
  end if;
  if v_url is not null and v_url !~ '^https://[a-z0-9]+\.supabase\.co/storage/v1/object/public/customer-photos/' then
    return jsonb_build_object('ok', false, 'reason', 'bad_url');
  end if;

  update public.customers
     set photo_url = v_url, updated_at = now()
   where id = v_row.id;

  return jsonb_build_object('ok', true, 'cleared', v_url is null);
end $function$;

revoke all on function public.public_customer_set_photo(text, text) from public;
grant execute on function public.public_customer_set_photo(text, text) to anon, authenticated, service_role;
