// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    // ===== v1.25.4 — read BOTH naming conventions =====
    // This read process.env only, under the un-prefixed names. Vite does not
    // copy .env into process.env; it inlines VITE_* into import.meta.env at
    // BUILD time. So on a server that was not given explicit environment
    // variables, both of these were undefined and every server function died
    // with "Missing Supabase environment variable(s)" — which is what broke
    // Super Admin restaurant provisioning while the browser worked fine.
    //
    // The publishable key is client-safe by design (it is already in the
    // browser bundle), so falling back to the VITE_ names costs nothing.
    // The SERVICE ROLE key is a different matter and must never be read this
    // way — see client.server.ts.
    // ===== v1.25.11 — bindings, not just process.env =====
    // Same trap as client.server.ts: Cloudflare Workers have no populated
    // process.env, so a correctly-set variable read only from there looks
    // missing. serverEnv() checks process.env, then the Workers binding.
    // The publishable key is client-safe, so falling back to the build-time
    // VITE_ value is fine here (it is already in the browser bundle).
    const viteEnv = (import.meta as any).env ?? {};
    const { serverEnv } = await import('./serverEnv');

    const SUPABASE_URL =
      (await serverEnv('SUPABASE_URL')) || viteEnv.VITE_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      (await serverEnv('SUPABASE_PUBLISHABLE_KEY', 'SUPABASE_ANON_KEY'))
      || viteEnv.VITE_SUPABASE_PUBLISHABLE_KEY
      || viteEnv.VITE_SUPABASE_ANON_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. `
        + 'Set them in .env (build time) or on your host. Supabase is the only backend.';
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
