// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { serverEnv, describeEnvSources } from './serverEnv';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

async function createSupabaseAdminClient() {
  // ===== v1.25.11 — read bindings, not just process.env =====
  // Cloudflare Workers deliver secrets as bindings; process.env is an empty
  // shim there. Reading only process.env made a correctly-configured Secret
  // look missing. serverEnv() checks process.env first (so .env.local still
  // wins in dev), then the Workers binding.
  const SUPABASE_URL = await serverEnv('SUPABASE_URL', 'VITE_SUPABASE_URL')
    ?? (import.meta as any).env?.VITE_SUPABASE_URL;

  // The SERVICE ROLE key must never be readable from import.meta.env: that
  // would inline it into the browser bundle and expose every tenant.
  const SUPABASE_SERVICE_ROLE_KEY =
    await serverEnv('SUPABASE_SERVICE_ROLE_KEY', 'SUPABASE_SECRET_KEY');

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message =
      `Missing server-side Supabase configuration: ${missing.join(', ')}. `
      + 'This is the SERVICE ROLE key, needed for admin work such as creating a '
      + "restaurant owner's login. Get it from Supabase Dashboard -> Project "
      + 'Settings -> API Keys -> service_role (or the secret key, sb_secret_...). '
      + 'On Cloudflare Pages add it under Settings -> Variables and secrets as a '
      + 'SECRET in the Production environment, then REDEPLOY - secrets only apply '
      + 'to new deployments. For local dev put it in .env.local. Never give it a '
      + 'VITE_ prefix and never commit it: it bypasses Row Level Security. '
      + `[env sources: ${await describeEnvSources()}]`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: { fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY) },
    auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
  });
}

let _supabaseAdmin: Awaited<ReturnType<typeof createSupabaseAdminClient>> | undefined;

/**
 * Server-side Supabase client with the service role - bypasses RLS.
 *
 * SECURITY: trusted server-side operations only, never client code.
 * Usage: const { getSupabaseAdmin } = await import('@/integrations/supabase/client.server');
 *        const admin = await getSupabaseAdmin();
 *
 * This is async because resolving the key may require reading a Cloudflare
 * binding, which is an async import. The old synchronous Proxy could not do
 * that, which is why the key appeared missing on Workers.
 */
export async function getSupabaseAdmin() {
  if (!_supabaseAdmin) _supabaseAdmin = await createSupabaseAdminClient();
  return _supabaseAdmin;
}
